/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal development and kept here so
// type-aware tooling has the expected project shape before the first install.
