export const NRW_SOURCE_TRUTH = {
  business: "Nashville Resin Worx",
  repository: "Strategic-Minds/NASHVILLERESINWORX",
  websitePurpose: "Generate qualified decorative surface leads.",
  primaryCta: "Get My Free Estimate",
  leadDestination: "info@epoxywillchangeyourlife.com",
  deployment: "Vercel",
  framework: "Next.js 15",
  styling: "Tailwind CSS",
  pwaRequired: true,
  socialRoute: "Metricool",
  brand: {
    tagline: "Epoxy - Wood - Metal - Concrete - Stone",
    position: "Premium custom decorative surfaces.",
    personality: ["premium", "professional", "creative", "industrial", "luxury", "craftsmanship"],
    accent: "Metallic Resin Blue",
    secondary: ["Copper", "Steel", "Silver", "White", "Black"],
    forbidden: ["lime green", "neon green UI", "rustic brown themes", "generic contractor layouts"],
  },
  services: [
    "Metallic Epoxy",
    "Flake Systems",
    "Concrete Staining",
    "Polished Concrete",
    "Countertops",
    "River Tables",
    "Decorative Concrete",
    "Stone Surfaces",
  ],
};
